### ISSUE TITLE
Still normal ip 

### ISSUE THREAD

**Issue by FTBSchnitzel** [anbuchelva/Pi-hole-and-Wireguard-on-Oracle-Cloud-always-free-tier#10]
Everything is working fine but i still have my normal ip
interface: wg0
  public key: SGoNwhrG8nka9Id0gDf1UHWykz8qDwI12QK9HhxQIHU=
  private key: (hidden)
  listening port: 51515

peer: RMCsihvA1PMyIn0oHqSMbjl6esyeK7zqYvI2nRcLY2M=
  preshared key: (hidden)
  endpoint: 94.31.85.235:59709
  allowed ips: 10.66.66.3/32, fd42:42:42::3/128
  latest handshake: 24 seconds ago
  transfer: 930.98 KiB received, 3.06 MiB sent

peer: 3maoP5rq4KQvhSTZR3vBxjGlWwj1USaCMuBuZE2NQCo=
  preshared key: (hidden)
  allowed ips: 10.66.66.2/32, fd42:42:42::2/128
ubuntu@vpn:~$ ^C
ubuntu@vpn:~$ sudo wg
interface: wg0
  public key: SGoNwhrG8nka9Id0gDf1UHWykz8qDwI12QK9HhxQIHU=
  private key: (hidden)
  listening port: 51515

peer: RMCsihvA1PMyIn0oHqSMbjl6esyeK7zqYvI2nRcLY2M=
  preshared key: (hidden)
  endpoint: 94.31.85.235:49448
  allowed ips: 10.66.66.3/32, fd42:42:42::3/128
  latest handshake: 37 seconds ago
  transfer: 1.01 MiB received, 3.18 MiB sent

peer: 3maoP5rq4KQvhSTZR3vBxjGlWwj1USaCMuBuZE2NQCo=
  preshared key: (hidden)
  allowed ips: 10.66.66.2/32, fd42:42:42::2/128

  pihole status
  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled

**Comment by anbuchelva** [comment]
Check point no 6 (just noticed no 6 is appearing twice in the guide, check the 2nd one) on this guide.

https://github.com/anbuchelva/Pi-hole-and-Wireguard-on-Oracle-Cloud-always-free-tier/blob/master/ORACLE-CLOUD.md#install-pi-hole-and-wireguard

**Comment by anbuchelva** [comment]
> Check point no 6 (just noticed no 6 is appearing twice in the guide, check the 2nd one) on this guide.
> 
> https://github.com/anbuchelva/Pi-hole-and-Wireguard-on-Oracle-Cloud-always-free-tier/blob/master/ORACLE-CLOUD.md#install-pi-hole-and-wireguard

Don't know commenting from mobile picks the right link. This is what I have mentioned in the guide


> Once your device is connected via Wireguard, all your DNS requests will flow through Pi-Hole. Your device will be identified by its IPv6 address in Pi-Hole's admin interface, which will be accessible at both http://[fd42:42:42::1]/admin and http://10.66.66.1/admin. The default configuration (which is the recommended configuration) for all VPN profiles is Split Tunnel. If you wish to route all your traffic through the VPN (Full Tunnel), edit the Allowed IPs on your Client Profile on your device to read 0.0.0.0/0, ::/0.

**Comment by anbuchelva** [comment]
@Schnitzelflo44 can you confirm whether you got it. So I can close the issue.
