### ISSUE TITLE
Pi-hole error

### ISSUE THREAD

**Issue by franciscosyz** [anbuchelva/Pi-hole-and-Wireguard-on-Oracle-Cloud-always-free-tier#2]
Hi,
encountered this error during installation and did not install pi-hole
can i get some help?
Oracle cloud
Server Ubuntu 22.04
``
[✓] Enabling lighttpd service to start on reboot...
  [✓] Creating user 'pihole'

  [i] FTL Checks...

  [✓] Detected AArch64 (64 Bit ARM) processor
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...pihole-FTL-aarch64-linux-gnu: FAILED
sha1sum: WARNING: 1 computed checksum did NOT match
  [✗] Downloading and Installing FTL
   Error: Download of https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-aarch64-linux-gnu failed (checksum error)
  [✗] FTL Engine not installed
./setup.sh: line 299: pihole: command not found
``

**Comment by anbuchelva** [comment]
You can install pi-hole manually running the following code

`curl -sSL https://install.pi-hole.net | bash`

I'll check on the ARM platform when i have time.

If you want to reinstall from the scratch, just delete the `/etc/wireguard` and rerun `setup.sh`  as root user.

**Comment by franciscosyz** [comment]
> You can install pi-hole manually running the following code
> 
> `curl -sSL https://install.pi-hole.net | bash`
> 
> I'll check on the ARM platform when i have time.
> 
> If you want to reinstall from the scratch, just delete the `/etc/wireguard` and rerun `setup.sh` as root user.

Many thanks, i did exactly that and work !
