### ISSUE TITLE
cannot connect to web ui

### ISSUE THREAD

**Issue by nyannoying1337** [anbuchelva/Pi-hole-and-Wireguard-on-Oracle-Cloud-always-free-tier#3]
Hello, i followed the steps and cant connect to the WebUI "Cant reach website" any idea what could have gone wrong?

**Comment by anbuchelva** [comment]
May i know what URL you are trying to access? Are you sure wireguard is working fine?

**Comment by nyannoying1337** [comment]
i tried to access it via http://10.66.66.1/admin

**Comment by anbuchelva** [comment]
have you opened the port 80 in oracle OCI?
Are you sure the wireguard is working fine?

**Comment by nyannoying1337** [comment]
Yep its Open and i checked that its working

Anbuselvan Palaniyandi ***@***.***> schrieb am Sa., 28. Jan.
2023, 12:49:
