### ISSUE TITLE
Issue with Wireguard and PiHole

### ISSUE THREAD

**Issue by addreeh** [anbuchelva/Pi-hole-and-Wireguard-on-Oracle-Cloud-always-free-tier#4]
When I finished the installation, through the VPN I get internet connection, I have the server allocated in France, but I still having an IP from my country and I can not enter in the PiHole admin page.
![image](https://user-images.githubusercontent.com/74270582/216836128-df78fd7c-6309-4209-8439-fd1a9f32e9b7.png)

**Comment by anbuchelva** [comment]
How do you configure your clients?  

By default the pihole installation is done as split tunnel method, the IP of your client system will not change. If you expect it to be changed, refer this [link](https://github.com/anbuchelva/Pi-hole-and-Wireguard-on-Oracle-Cloud-always-free-tier/blob/master/ORACLE-CLOUD.md#install-pi-hole-and-wireguard) , point 6. The internet speed will be slow on the oracle free tier.

Share the output of the following commands from your server.
`sudo wg`
`pihole status`

**Comment by addreeh** [comment]
if i connect the vpn i have internet but i still have the same public ip than before
![image](https://user-images.githubusercontent.com/74270582/218325351-3d29a498-b90b-4a7f-9762-eac47a24dcbf.png)
i can not access to the pihole interface
![image](https://user-images.githubusercontent.com/74270582/218325381-544841fc-36c3-47e8-ab9b-c5f34f5d8012.png)
