### ISSUE TITLE
Only assigning IPv4 to peers

### ISSUE THREAD

**Issue by zqyr** [anbuchelva/Pi-hole-and-Wireguard-on-Oracle-Cloud-always-free-tier#8]
First, thanks for the wonderful setup script. Made life a lot easier.

My devices (peers) are making DNS lookups via IPv4 and IPv6. They show up as two separate clients in Pi-hole server, as it does not merge them together. I checked out Pi-Hole's community forums and came across [this](https://discourse.pi-hole.net/t/adding-alias-clients-to-pi-hole-ftl/37084/28). Now, since this is a Pi-Hole limitation, my other option is to disable peers to be assigned (and use) IPv6 address/routing completely.

My question here is,

1. Is it safe to leave IPv6 address as blank, when running setup.sh again to create tunnel config file for new peers

2. Say if we disable IPv6 addressing/routing on this wireguard network, would there be any IP leak **iff** peers made DNS queries via IPv6 route?

Let me know if this question makes any sense.

**Comment by anbuchelva** [comment]
I suggest you post this question in pihole support page or in their reddit.

**Comment by zqyr** [comment]
Thanks. I'm gonna answer my own question,

> 2. Say if we disable IPv6 addressing/routing on this wireguard network, would there be any IP leak iff peers made DNS queries via IPv6 route?

Yes. There would be IP leak, in the sense that IPv6 DNS queries would be resolved outside of Wireguard+PiHole Tunnel, if I retroactively disable IPv6 addressing/routing.

-- --

I've posted on Pi-Hole community, to find a workaround for having separate logging of DNS queries on their dashboard. You can follow along the discussion right [here](https://discourse.pi-hole.net/t/merging-ipv4-and-ipv6-dns-lookups-for-a-given-client/63267).

Now, what I'm not sure - if someone seeks to use WireGuard+PiHole tunnel for IPv4 routing, what could they tweak in setup.sh to ensure that Wireguard network with IPv4 is configured and the peer config generation step reflects this new IPv4 only configuration edge case.

**Comment by zqyr** [comment]
If anyone else is interested, [here's a partial solution.](https://discourse.pi-hole.net/t/merging-ipv4-and-ipv6-dns-lookups-for-a-given-client/63267/20?u=leo) 

There's a bug associated to this workaround, as reported [here](https://discourse.pi-hole.net/t/merging-ipv4-and-ipv6-dns-lookups-for-a-given-client/63267/21?u=leo).

Note that you can still access everything from Query Log, from the sidebar menu.
